export const convertToEmbedUrl = (url) => {
    const regex = /(?:https?:\/\/)?(?:www\.)?(?:youtube\.com\/(?:[^\/\n\s]+\/\S+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([a-zA-Z0-9_-]{11})/;
    const match = url.match(regex);
    
    if (match && match[1]) {
      return `https://www.youtube.com/embed/${match[1]}`;
    }
    return null; 
  };
export const moviesData = [
    {
        id: 1,
        title: "Her",
        rate: 4,
        description: "In a near future, a lonely writer develops an unlikely relationship with an operating system designed to meet his every need.",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMjA1Nzk0OTM2OF5BMl5BanBnXkFtZTgwNjU2NjEwMDE@._V1_.jpg",
        trailer: "https://www.youtube.com/embed/6QRvTv_tpw0",
    },
    {
        id: 2,
        title: "The Lobster",
        rate: 3,
        description: "In a dystopian near future, single people must find a partner in forty-five days or are transformed into beasts.",
        posterUrl: "https://i.pinimg.com/originals/43/9b/19/439b192bedc27cfaa0ec1cc787db800d.jpg",
        trailer: "https://www.youtube.com/embed/vU29VfayDMw",
    },
    {
        id: 3,
        title: "The Pianist",
        rate: 5,
        description: "A Polish Jewish musician struggles to survive the destruction of the Warsaw ghetto during World War II.",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BOWRiZDIxZjktMTA1NC00MDQ2LWEzMjUtMTliZmY3NjQ3ODJiXkEyXkFqcGdeQXVyNjU0OTQ0OTY@._V1_.jpg",
        trailer: "https://www.youtube.com/embed/BFwGqLa_oAo",
    },
    {
        id: 4,
        title: "Avengers: Endgame",
        rate: 1,
        description: "The Avengers assemble once more to reverse Thanos' actions and restore balance to the universe.",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_.jpg",
        trailer: "https://www.youtube.com/embed/TcMBFSGVi1c",
    },
    {
        id: 5,
        title: "Gangs of New York",
        rate: 3,
        description: "Amsterdam Vallon returns to New York City seeking revenge against Bill the Butcher, his father's killer.",
        posterUrl: "https://img7.cdn.cinoche.com/images/14aa038469eaf2ca96dbc3da4182428c.jpg",
        trailer: "https://www.youtube.com/embed/qHVUPri5tjA",
    },
    {
        id: 6,
        title: "Inheritance",
        rate: 3,
        description: "A wealthy patriarch's death leaves his daughter with a shocking secret inheritance.",
        posterUrl: "https://i1.wp.com/setthetape.com/wp-content/uploads/2020/06/Inheritance-POSTER.jpg?resize=225%2C300&ssl=1",
        trailer: "https://www.youtube.com/embed/bkaWQ5HlE5U",
    },
    {
        id: 7,
        title: "The Fountain",
        rate: 4,
        description: "A scientist searches for a medical breakthrough to save his cancer-stricken wife.",
        posterUrl: "https://upload.wikimedia.org/wikipedia/en/e/ee/Fountain_poster_1.jpg",
        trailer: "https://www.youtube.com/embed/m8IlyFCbNZg",
    },
    {
        id: 8,
        title: "Spotlight",
        rate: 4,
        description: "The Boston Globe uncovers a scandal of child molestation within the Catholic Church.",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMjIyOTM5OTIzNV5BMl5BanBnXkFtZTgwMDkzODE2NjE@._V1_.jpg",
        trailer: "https://www.youtube.com/embed/EwdCIpbTN5g",
    },
    {
        id: 9,
        title: "Avengers: Infinity War",
        rate: 1,
        description: "The Avengers must sacrifice all to defeat Thanos before he destroys the universe.",
        posterUrl: "https://m.media-amazon.com/images/I/81V1KTnYKwL._AC_UF1000,1000_QL80_.jpg",
        trailer: "https://www.youtube.com/embed/6ZfuNTqbHE8",
    },
    {
        id: 10,
        title: "The Machinist",
        rate: 4,
        description: "An industrial worker doubts his sanity after not sleeping for a year.",
        posterUrl: "https://upload.wikimedia.org/wikipedia/en/b/b9/The_Machinist_poster.JPG",
        trailer: "https://www.youtube.com/embed/gxH8U_49QnU",
    },
    {
        id: 11,
        title: "Skyfall",
        rate: 1,
        description: "James Bond must track down a threat to MI6 while dealing with M's past.",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMWZiNjE2OWItMTkwNy00ZWQzLWI0NTgtMWE0NjNiYTljN2Q1XkEyXkFqcGdeQXVyNzAwMjYxMzA@._V1_.jpg",
        trailer: "https://www.youtube.com/embed/6kw1UVovByw",
    },
    {
        id: 12,
        title: "Parasite",
        rate: 3,
        description: "Greed and class discrimination threaten the relationship between two families.",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BYWZjMjk3ZTItODQ2ZC00NTY5LWE0ZDYtZTI3MjcwN2Q5NTVkXkEyXkFqcGdeQXVyODk4OTc3MTY@._V1_UY1200_CR90,0,630,1200_AL_.jpg",
        trailer: "https://www.youtube.com/embed/SEUXfv87Wpk",
    },
    {
        id: 13,
        title: "The Social Network",
        rate: 4,
        description: "The story of the founding of Facebook and the legal battles that followed.",
        posterUrl: "https://cdn11.bigcommerce.com/s-yzgoj/images/stencil/1280x1280/products/2883213/5963058/MOVCB26563__02531.1679605821.jpg?c=2",
        trailer: convertToEmbedUrl("https://youtu.be/lB95KLmpLR4?si=Ncf-8x-DyP-q2Wd-"),
    },
    {
        id: 14,
        title: "Mad Max: Fury Road",
        rate: 5,
        description: "In a post-apocalyptic wasteland, Max teams up with Furiosa to escape a tyrant.",
        posterUrl: "https://mir-s3-cdn-cf.behance.net/project_modules/1400/1e70eb70042969.5b966f9d4c7a0.jpg",
        trailer: convertToEmbedUrl("https://youtu.be/hEJnMQG9ev8?si=TrJjkwlOw7pEl27N"),
    },
    {
        id: 15,
        title: "The Shape of Water",
        rate: 4,
        description: "A mute woman forms a unique relationship with a mysterious aquatic creature.",
        posterUrl: "https://ejdelosreyes.wordpress.com/wp-content/uploads/2018/03/the_shape_of_water_fan_art_by_rafaelskywalker-dbyu7u6.jpg?w=1000",
        trailer: convertToEmbedUrl("https://youtu.be/XFYWazblaUA?si=eEVekq1duXZupTa4"),
    },
    {
        id: 16,
        title: "Get Out",
        rate: 5,
        description: "A young African American visits his white girlfriend's family, uncovering unsettling secrets.",
        posterUrl: "https://static01.nyt.com/images/2018/03/03/arts/03get-out-posters-print2/merlin_134418533_a3f2d747-aa59-4ba1-92e6-4376f85587eb-superJumbo.jpg",
        trailer: convertToEmbedUrl("https://youtu.be/DzfpyUB60YY?si=m_tHEi3GjPA3FNLm"),
    },
    {
        id: 17,
        title: "The Grand Budapest Hotel",
        rate: 4,
        description: "A comedic caper revolving around a hotel concierge and his apprentice.",
        posterUrl: "https://m.media-amazon.com/images/I/713kiC-8JhL._AC_UF1000,1000_QL80_.jpg",
        trailer: convertToEmbedUrl("https://youtu.be/1Fg5iWmQjwk?si=TJIhaor0aq9jSAxn"),
    },
    {
        id: 18,
        title: "Inside Out",
        rate: 5,
        description: "A young girl navigates her emotions as her family moves to a new city.",
        posterUrl: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQsOChzbAVxomR8C_1Lwz_wrlssxRFd_lVWtA&s",
        trailer: convertToEmbedUrl("https://youtu.be/yRUAzGQ3nSY?si=PK3xHFC6sQ6uOqz0"),
    },
    {
        id: 19,
        title: "Joker",
        rate: 3,
        description: "A failed comedian's descent into madness leads to the rise of the iconic villain.",
        posterUrl: "https://m.media-amazon.com/images/I/51R9B-uhtJL._AC_UF1000,1000_QL80_.jpg",
        trailer: convertToEmbedUrl("https://youtu.be/zAGVQLHvwOY?si=yf_QqBvy7ldCHWq4"),
    },
    {
        id: 20,
        title: "The Irishman",
        rate: 4,
        description: "A mob hitman recalls his possible involvement with the slaying of Jimmy Hoffa.",
        posterUrl: "https://m.media-amazon.com/images/M/MV5BMTY2YThkNmQtOWJhYy00ZDc3LWEzOGEtMmQwNzM0YjFmZWIyXkEyXkFqcGc@._V1_.jpg",
        trailer: convertToEmbedUrl("https://youtu.be/WHXxVmeGQUc?si=AsEGpBDahB372RTd"),
    },
    {
        id: 21,
        title: "Dunkirk",
        rate: 5,
        description: "Allied soldiers are surrounded by the German Army during World War II and evacuated during a fierce battle.",
        posterUrl: "https://img.fruugo.com/product/6/53/29794536_max.jpg",
        trailer: convertToEmbedUrl("https://youtu.be/F-eMt3SrfFU?si=hIaQWUvpqkD9YB2g"),
    },
    {
        id: 22,
        title: "The Trial of the Chicago 7",
        rate: 4,
        description: "The story of the trial following the protests at the 1968 Democratic National Convention.",
        posterUrl: "https://m.media-amazon.com/images/I/71gZwETfjuL._AC_UF894,1000_QL80_.jpg",
        trailer: convertToEmbedUrl("https://youtu.be/FVb6EdKDBfU?si=S9it_x5Xke6j2-_1"),
    },
    {
        id: 23,
        title: "Knives Out",
        rate: 4,
        description: "A detective investigates the death of a patriarch at his family gathering.",
        posterUrl: "https://m.media-amazon.com/images/I/91MeoYwAP8L._AC_UF894,1000_QL80_.jpg",
        trailer: convertToEmbedUrl("https://youtu.be/qGqiHJTsRkQ?si=XrwaAnAf2Ymw8_tG"),
    },
    {
        id: 24,
        title: "A Beautiful Mind",
        rate: 5,
        description: "The story of John Nash, a brilliant but asocial mathematician who develops schizophrenia.",
        posterUrl: "https://cdn11.bigcommerce.com/s-yzgoj/images/stencil/500x659/products/2916515/5898452/MOVGI6622__23721.1679556130.jpg?c=2",
        trailer: convertToEmbedUrl("https://youtu.be/EajIlG_OCvw?si=71Y6jfGysWbdV01W"),
    }
];
